<a href="https://colab.research.google.com/github/moheetjari/PythonProgramming/blob/main/WineQualityWhiteMultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [24]:
data = pd.read_csv('/content/WineQualityWhite.csv')
data.head()
X = data[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
y = data[['quality']]
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.0              0.27         0.36  ...       0.45      8.8        6
1            6.3              0.30         0.34  ...       0.49      9.5        6
2            8.1              0.28         0.40  ...       0.44     10.1        6
3            7.2              0.23         0.32  ...       0.40      9.9        6
4            7.2              0.23         0.32  ...       0.40      9.9        6

[5 rows x 12 columns]

In [25]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
#Co-efficient
m = regr.coef_
m

array([[ 6.55199614e-02, -1.86317709e+00,  2.20902007e-02,
         8.14828026e-02, -2.47276537e-01,  3.73276519e-03,
        -2.85747419e-04, -1.50284181e+02,  6.86343742e-01,
         6.31476473e-01,  1.93475697e-01]])

In [27]:
#intercept
c = regr.intercept_
c

array([150.19284248])

In [28]:
regr.predict(X)

array([[5.5626578 ],
       [5.21687319],
       [5.7664803 ],
       ...,
       [5.34192079],
       [6.57129362],
       [6.3473428 ]])